kind: Pod
apiVersion: v1
metadata:
  name: nginx
spec:
  nodeSelector:
    hardware: GPU
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: hardware
    operator: Equal
    value: GPU
    effect: NoSchedule