kind: Pod
apiVersion: v1
metadata: 
  name: affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: hardware
            operator: In
            values:
            - GPU
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: hardware
    operator: Equal
    value: GPU
    effect: NoSchedule