kind: Pod
apiVersion: v1
metadata:
  name: affinity-3
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: hardware
            operator: In
            values:
            - CPU
      - weight: 2
        preference:
          matchExpressions:
          - key: hardware
            operator: In
            values:
            - GPU 
containers:
  - name: nginx
    image: nginx