kind: Pod
apiVersion: v1
metadata:
  name: affinity_3
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        prefference:
          matchExpressions:
          - key: hardware
            operator: In
            values:
            - CPU
  containers:
  - name: nginx
    image: nginx