kind: Pod
apiVersion: v1
metadata:
  name: pod-1
  labels:
    purpose: Affinity
spec:
  containers:
  - name: nginx
    image: nginx
---
kind: Pod
apiVersion: v1
metadata:
  name: pod-2
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: topology.kubernetes.io/zone
        labelSelector:
          matchExpressions:
          - key: purpose
            operator: In
            values:
            - Affinity
  containers:
  - name: nginx
    image: nginx